#!/usr/bin/env bash
# SessionStart hook: surfaces configured credentials and writes a sourceable .agentcraft.env
# file to the project directory so subprocesses and the user can pick up env vars.

MLFLOW_URI="${CLAUDE_PLUGIN_OPTION_MLFLOW_TRACKING_URI:-}"
ANTHROPIC_KEY="${CLAUDE_PLUGIN_OPTION_ANTHROPIC_API_KEY:-}"
OPENAI_KEY="${CLAUDE_PLUGIN_OPTION_OPENAI_API_KEY:-}"

OUT_FILE="${CLAUDE_PROJECT_DIR}/.agentcraft.env"

{
  echo "# Generated by agentcraft plugin — do not commit"
  [[ -n "$MLFLOW_URI" ]] && echo "export MLFLOW_TRACKING_URI='${MLFLOW_URI}'"
  [[ -n "$ANTHROPIC_KEY" ]] && echo "export ANTHROPIC_API_KEY='${ANTHROPIC_KEY}'"
  [[ -n "$OPENAI_KEY" ]] && echo "export OPENAI_API_KEY='${OPENAI_KEY}'"
} > "$OUT_FILE"

CONFIGURED=()
[[ -n "$MLFLOW_URI" ]] && CONFIGURED+=("MLflow (${MLFLOW_URI})")
[[ -n "$ANTHROPIC_KEY" ]] && CONFIGURED+=("Anthropic")
[[ -n "$OPENAI_KEY" ]] && CONFIGURED+=("OpenAI")

if [[ ${#CONFIGURED[@]} -gt 0 ]]; then
  echo "AgentCraft: credentials written to .agentcraft.env — source it before running agents:"
  echo "  source .agentcraft.env"
  echo "  Configured: $(IFS=', '; echo "${CONFIGURED[*]}")"
else
  echo "AgentCraft: no credentials configured — run 'claude plugin config agentcraft' to add API keys."
fi
