#!/usr/bin/env bash
# SessionStart hook: surfaces configured credentials and writes a sourceable .agentcraft.env
# file to the project directory so subprocesses and the user can pick up API keys.

LANGSMITH_KEY="${CLAUDE_PLUGIN_OPTION_LANGSMITH_API_KEY:-}"
LANGSMITH_PROJ="${CLAUDE_PLUGIN_OPTION_LANGSMITH_PROJECT:-default}"
ANTHROPIC_KEY="${CLAUDE_PLUGIN_OPTION_ANTHROPIC_API_KEY:-}"
OPENAI_KEY="${CLAUDE_PLUGIN_OPTION_OPENAI_API_KEY:-}"

OUT_FILE="${CLAUDE_PROJECT_DIR}/.agentcraft.env"

{
  echo "# Generated by agentcraft plugin — do not commit"
  [[ -n "$LANGSMITH_KEY" ]] && echo "export LANGSMITH_API_KEY='${LANGSMITH_KEY}'"
  [[ -n "$LANGSMITH_PROJ" ]] && echo "export LANGSMITH_PROJECT='${LANGSMITH_PROJ}'"
  [[ -n "$LANGSMITH_KEY" ]] && echo "export LANGSMITH_TRACING=true"
  [[ -n "$ANTHROPIC_KEY" ]] && echo "export ANTHROPIC_API_KEY='${ANTHROPIC_KEY}'"
  [[ -n "$OPENAI_KEY" ]] && echo "export OPENAI_API_KEY='${OPENAI_KEY}'"
} > "$OUT_FILE"

CONFIGURED=()
[[ -n "$LANGSMITH_KEY" ]] && CONFIGURED+=("LangSmith (project: ${LANGSMITH_PROJ})")
[[ -n "$ANTHROPIC_KEY" ]] && CONFIGURED+=("Anthropic")
[[ -n "$OPENAI_KEY" ]] && CONFIGURED+=("OpenAI")

if [[ ${#CONFIGURED[@]} -gt 0 ]]; then
  echo "AgentCraft: credentials written to .agentcraft.env — source it before running agents:"
  echo "  source .agentcraft.env"
  echo "  Configured: $(IFS=', '; echo "${CONFIGURED[*]}")"
else
  echo "AgentCraft: no credentials configured — run 'claude plugin config agentcraft' to add API keys."
fi
